- BGCF_Testing.md
- Gemfile.lock
- README.md
- lib/test-definition.rb
- lib/tests/basic-call.rb
- lib/tests/offnet.rb
This adds:
* a test where I ring tel:1234 and check that it routes to sip:1234@domain. This is pretty basic function and should work everywhere.
* a test where I ring a user-defined number and check that it routes back to me on port 5072.
The latter is a generically useful test for checking some BGCF configuration. For example, to test basic BGCF routing (assuming I'm running the tests from 10.0.0.1), I'd:
* Set the following route in bgcf.json:
```
{   "name" : "Test 1",
"domain" : "otherdomain",
"route" : ["sip:10.0.0.1:5072;transport=tcp"]
}
```
* Set up the following ENUM entry:
`1.0.0.0.0.0.0.0.0.1.e164.arpa.	3600	IN	NAPTR	1 1 "u" "E2U+sip" "!(^.*$)!sip:\\1@otherdomain!"`
*  Run `rake test[deployment] TESTS="Off-net*" TRANSPORT=TCP OFF_NET_TEL=1000000001`
To test NP, I'd:
* Set the …
> [Reviewer: Ellie] Live tests for tel: URIs and BGCF

- lib/tests/gemini.rb
I've:
* updated the checks around Accept/Reject-Contact headers (reflecting the change from +sip.phone to +sip.with-twin and the extra `;explicit;require` on the `g.3gpp.ics` fork)
* made the endpoint representing a mobile register with the `g.3gpp.ics` contact parameter
This fixes the Gemini tests when I run them against staging. The `Filtering - RFC3841 example` test is failing, but I don't *think* that's related.
> [Reviewer: Graeme] Update Gemini tests to reflect filtering changes

- schemas/reginfo.xsd
- schemas/xml.xsd
Change as discussed. Previously we were some times failing to import xml.xsd by the looks of it.
> Reviewer AMC: Create a local copy of xml.xsd so we can always find it

- lib/live-test.rb
Simply sort the test definition files by name.  This has the nice (but fluky) property of running the basic tests first so the user can bail out if they're broken (as other tests are going to fail too anyway).
> Reviewer Matt - Sort tests by filename so basic tests run first

- lib/quaff-endpoint.rb
This allows us to have a Perimeta where clients on port 5059 connect to staging and clients on port 5060 connect to dogfood. (This means we can just have one VM, which is half the cost of having two.)
Tested live, both specifying PROXY_PORT and not specifying it.
> [Reviewer: Graeme] Allow PROXY_PORT to be specified

- lib/ellis.rb
This just makes it easier to diagnose issues like https://github.com/Metaswitch/ellis/issues/174 and https://github.com/Metaswitch/ellis/issues/175, by catching the exceptions and printing out more HTTP-level detail.
Output looks like:
```
$ bundle exec rake test[cw-ngv.com] TESTS="Basic Call - Mainline"
Basic Call - Mainline (TCP) - (6505550024, 6505550050) Passed
Basic Call - Mainline (UDP) - (6505550051, 6505550097) Passed
Listing existing numbers failed with HTTP code 502, body {"status": 502, "message": "Bad Gateway", "reason": "Upstream request failed", "detail": {"Upstream error": "HTTP 404: Not Found"}, "error": true}
```
> [Reviewer: Ellie] Print out Ellis errors in more detail

- BGCF_Testing.md
- README.md
- lib/test-definition.rb
This moves the live tests to run using TCP by default. 
Tested live
> [Reviewer: Alex] Run the live tests under TCP by default

- lib/tests/subscribe.rb
As I think we've discussed before, this test fails unusually often (7 times out of 408 runs) so there might be a bug here. I've added extra diagnostics to help see what's going on.
I reversed the if test to force it to fail so I could see the diags:
```
SUBSCRIBE - Registration timeout (UDP) - (6515550001, 6515550018) Failed
Endpoint threw exception:
- NOTIFY responses have same or non-incrementing CSeq - first one had '3 NOTIFY', second one had '4 NOTIFY'
- /home/ubuntu/clearwater-live-test/lib/tests/subscribe.rb:215:in `block (2 levels) in <top (required)>'
```
> [Reviwer: Ellie] Add diags to help track down SUBSCRIBE/NOTIFY failure

- lib/live-test.rb
- lib/test-definition.rb
I've sometimes had a couple of problems when looking at the output of clearwater-live-test:
* when cutting the release, the tests usually scroll off the page and I have to scroll back up and hunt through to see if I can spot any failures
* when debugging tests, especially if I start some tests and come back to it later, I don't always know when the test failed and therefore when to search for diags
To improve this, I've made the test runner print out a summary:
```
2 failures out of 14 tests run
Basic Call - Mainline (UDP) at 2016-07-23 11:26:37 +0000
Basic Call - Mainline (UDP) at 2016-07-23 11:26:51 +0000
0 tests skipped
```
> [Reviewer: Graeme] End of test report

- lib/test-definition.rb
I hope you're the right person for this Rob; if not, my apologies.
Change made to fix the SNMP test, in the verify_snmp_stats function in test-definition.rb.
The OIDs were missing a .1/.2/.3 on the end to specify time period (previous 5s, current 5s, previous 5m respectively), which might have been added to the SNMP stats for Bono after these tests were written. 
I am not too familiar with these tests and was unsure what time period would be appropriate; I have specified previous 5 seconds for now, but this would be easy to change. 
I have tested these against a Clearwater deployment. Previously, testing with the SNMP=Y argument resulted in the "No SNMP responses from Bono" message for every test. Now they run without this message and without raising any errors.
> Fix Bono SNMP OIDs in verify_snmp_stats

- lib/tests/contact-filtering.rb
I ran this test 10 times plus on its own on my dev box and it failed every time. After my fix, I've run it 22 times and counting without it failing.
I haven't worked out *exactly* why the test was previous failing but this seems like a sensible fix. I assume that `recv_request` actually waits to receive the message, whereas the `no_new_calls` check obviously does not. Despite the sleep we still seemed to occasionally reach the `no_new_calls` check for binding 1 before the call arrived.
Fixes #128.
> Reviewer RKD: More reliable checking of forking

- lib/test-definition.rb
Tested by making `Basic Call - Mainline` throw an exception as soon as it gets an INVITE:
```
$ time bundle exec rake test[rkd.cw-ngv.com] TESTS="Basic Call - *"                             
Basic Call - Mainline (TCP) - (4155550031, 4155550454) Failed
Endpoint threw exception:
- RKD
- /home/ubuntu/clearwater-live-test/lib/tests/basic-call.rb:83:in `block (2 levels) in <top (required)>'
Terminating other threads after failure
Basic Call - SDP (TCP) - (4155550809, 4155550603) Passed
Basic Call - Tel URIs (TCP) - (4155550980, 4155550173) Passed
Basic Call - Unknown number (TCP) - (4155550514, 4155550844) Passed
Basic Call - Rejected by remote endpoint (TCP) - (4155550784, 4155550467) Passed
Basic Call - Messages - Pager model (TCP) - (4155550857, 4155550635) Passed
Basic Call - Pracks (TCP) …
```
> [Reviewer: Graeme] Fail test as soon as one thread throws an exception

- lib/quaff-monkey-patches.rb
Store of the routeset from the 200 OK so that we put the right routeset on when sending in-dialog requests.
Tested live.
> [Reviewer: RKD] Store the routeset from the 200 OK not the NOTIFY

- lib/tests/subscribe.rb
I saw a test failure where:
* I ran this test
* Sprout received the SUBSCRIBE at 16:51:47.998 with expiry=3
* Sprout sent the NOTIFY at 16:51:48.005 (a new second), so it had expiry=2
This seems reasonable so I've updated the test to cope with that. (I've also allowed expires=1 just in case.)
Tested in `irb`:
```
2.3.0 :017 > /active;expires=(1|2|3)/.match("active;expires=3")
=> #<MatchData "active;expires=3" 1:"3">
2.3.0 :018 > /active;expires=(1|2|3)/.match("active;expires=2")
=> #<MatchData "active;expires=2" 1:"2">
2.3.0 :020 > /active;expires=(1|2|3)/.match("timeout")
=> nil
```
> [Reviewer: Graeme] Cope with expires=2 instead of expires=3 in timing windows

- lib/test-definition.rb
~@rkd-msw, if you're unable to review, please pass to the appropriate person.~ Just noticed that Rob is on holiday for a week - resassigning. @AME2, if you're not the right person, could you please point me in the right direction? Thanks
This adds a begin/rescue block around `@quaff_cleanup_blk.call` in the cleanup after every test. If an exception is hit, we print a warning to screen including the exception, and then continue the main cleanup.
This fixes a problem where hitting an exception in the test-defined cleanup block silently exits the cleanup process, leaving un-terminated endpoints.
This is easiest to hit if registration errors occur - typical cleanup blocks include unregistering callers, and if they don't get the expected 401|200, they throw an exception and callers/endpoints …
> [Reviewer: AME2] Catch exceptions in quaff_cleanup_blk

- lib/live-test.rb
If you try to use bundler to package up and then install the live test dependencies locally, then the tests fail.  This is fixed by requiring `bunder/setup` at the start of the tests.
Applying upstream from private repository.
> Let tests run from bundled environment

- lib/test-definition.rb
For unreliable tests that still offer a useful regression check. By setting `repeat_on_failure` to x, the test must fail (x+1) times in a row to be logged as an overall failure. 
This is done by a recursive call to `run` if the return value of the first run is false, and if `repeat_on_failure` is above 0. Before each recursive call, we subtract 1 from `repeat_on_failure`. This will repeat on any failure in the `begin/ensure` block in `run`.
Note that the red `Failed` text will still appear next to each failed iteration, but the test will not be logged as an overall failure unless all iterations fail. Example output:
```
Unreliable Test (TCP) (iter 77) - (3335550272) Failed
Endpoint threw exception:
- Expected 200, got 400 (call ID 16553b4726407a8f8559da0a2acf92dc)
<exception backtrace> …
```
> [Reviewer: RKD] Add infra to retry test on failure

- lib/test-definition.rb
Fixes an oversight in #151.
I overlooked the fact that the entire test block of code is called again on recursively calling `run` - not just the setup, scenario and cleanup blocks. This makes it unusable, as `num_lives` will get altered/reset each time the test is retried if it added lives - leading to infinite loops if the test fails every time.
As an easy fix, this adds a `lives_used` counter to each instance, which is incremented on retry. Provided num_lives is set to a single value in the test block (e.g. `num_lives = 2`), this now functions as intended.
(As a clarity change, I also swapped `puts` for `print` so that the new number and success/fail print is on the same line as the new iteration text, instead of below it.)
This has been properly tested this time, against a mock test …
> [Reviewer: RKD] Fix infra to retry test on failure

- lib/tests/subscribe.rb
Alex,
https://github.com/Metaswitch/sprout/pull/1878 changes how we build Sprout NOTIFYs.
The live test checks for this in a really brittle way when it comes to checking whether we have a GRUU. I've made it more resilient by using xpath, instead of just assuming the first element is a GRUU.
For reference the XML body we see now looks like the following:
```
<?xml version="1.0" encoding="UTF-8"?>
<reginfo xmlns="urn:ietf:params:xml:ns:reginfo" xmlns:gr="urn:ietf:params:xml:ns:gruuinfo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ere="urn:3gpp:ns:extRegExp:1.0" version="0" state="full">
<registration aor="sip:6515550036@staging.cw-ngv.com" id="921170198579381024" state="active">
<contact id="&lt;urn:uuid:7c9db050-5076-5432-8e7b-f7faf3a118b9&gt;" state="active" …
```
> [Reviewer: Alex] Don't assume the GRUU is the second element in the contact XML

- lib/tests/subscribe.rb
Pull request #146 was merged 7 hours ago, containing a syntax error. This completely prevents any of our live tests from running.
This fixes the syntax error, just to get the tests running again. I'm not sure if there are any other issues with the test - it fails, as expected because the Sprout build (containing the accompanying code change) failed, so the functionality is missing from my test deployment.
> [No reviewer] Fix syntax error in subscribe.rb

- lib/test-definition.rb
- lib/tests/isc-interface.rb
`$HOSTNAME` is normally the local host, so this causes tests to be run incorrectly. Change it to use `$HOST_NAME`.
> [No reviewer] Fix HOSTNAME clash that wrongly triggered tests

- .gitmodules
- Dockerfile
- Gemfile
- Gemfile.lock
- README.md
This adds in a Dockerfile, to build a live test image. 
So that there weren't issues in pulling the quaff code down, i've re-instated it as a submodule. I wonder if we should do similar for Joker, but at the moment it isn't causing issues, so not too fussed.
I've built this on my docker build machine, and i can successfully exec into the container, and run the mainline live test successfully, so i'm happy that's working. Running the  full set now, just to check fully.
Now that we have this, i'm not really  sure how valuable it is, which is a bit of a shame, but i don't see any harm in having it. Should probably work out what we're going to use if for though...
> Docker build

- lib/test-definition.rb
If we hit an exception in the cleanup block, we should be failing the test - something has gone wrong with e.g. deregistration and we should highlight that with a test failure, instead of simply printing the exception to screen as we did before.
I haven't tested this code. I'm fairly confident that it should just work, but I suggest you try it out first @jack-atack. Also discuss it with the team to double check my assertion that hitting an issue in cleanup should always fail the test.
> [Reviewer: JA4] Fail test if there is an exception in the test-defined cleanup block

- lib/quaff-endpoint.rb
- lib/tests/basic-register.rb
Was also going to add a test for Registration expiry, but we already have one (that also checks that the correct notify is sent).   https://github.com/Metaswitch/clearwater-live-test/blob/master/lib/tests/subscribe.rb#L154-L220
> [Reviewer: Richard] Add emergency registration test

- lib/tests/subscribe.rb
A similar fix to #162, for the multiple SUBSCRIBEs test.
> [Reviewer: RKD] Sleep for a second to avoid a REGISTER which doesn't refresh

- README.md
- lib/test-definition.rb
- lib/tests/basic-register.rb
This test only succeeds against deployments that support emergency registrations (add a config option to signal that).
It isn't possible to de-reg an emergency registration and so previously the test used to leave it lying around which breaks subsequent tests.  Instead use a short registration expiry time (and add a config option to indicate whether this is supported).
> Fix emergency reg test

- lib/tests/urn.rb
This is just a find-and-replace on urn.rb to use `urn:service:sos` (defined in RFC5031, https://tools.ietf.org/html/rfc5031).
> Use urn:service:sos instead of urn:services:sos

- README.md
- Rakefile
- lib/tests/call-forking.rb
Adds some live tests for Call Forking, namely:
1. Register 2 bindings for the callee, check that they both ring and that when one answers the other's call is cancelled
1. Register 2 bindings for the callee, but have one of them be unresponsive to the INVITE. Check that the call can still complete to the other
1. Register 2 bindings for the callee, but have one of the become unresponsive after sending a 180 response. Check that the call can still complete to the other
Verified that these pass on the staging system, and that the flows are correct in SAS
I've added a new option to the environment: `PCSCF=PROXY` or `PCSCF=B2BUA` which controls whether we expect one or two 180 Ringing responses on the Call Forking tests. It defaults to `PROXY` here, as that's how Bono behaves.
> [Reviewer: Richard] Add Call Forking live tests

- lib/tests/subscribe.rb
It requires SHORT_REG=Y as it relies on a short registration time.
Also, remove the unnecessary sleep that can cause it to fail, and don't try to unregister the line that has an expired registration, because this may fail if the P-CSCF blocks it
> [Reviewer: Richard] Tweak the SUBSCRIBE - Registration Timeout test

- lib/tests/memento.rb
It must wait for the Ringing response in the same way that the ordinary Basic Call test does
Tested that the Memento tests now reliably pass.
> [No reviewer] Fix up memento basic call test
